verbs = [
    'being',
    'having',
    'doing',
    'saying',
    'going',
    'getting',
    'making',
    'thinking',
    'taking',
    'seeing',
    'coming',
    'using',
    'giving',
    'working',
    'calling',
    'asking',
    'holding',
    'putting',
    'pushing',
    'pulling',
    'placing',
    'walking',
    'running',
    'dancing',
    'singing',
    'keeping',
    'eating',
    'cooking',
    'finding',
    'moving',
    'bringing',
    'writing',
    'sitting',
    'sleeping',
    'standing',
    'meeting',
    'watching',
    'winning',
    'losing',
    'buying',
    'wearing',
    'baking'
]

prepositions = [
    'with',
    'on',
    'above',
    'below',
    'inside', # not 'in' since it is a keyword
    'outside',
    'near',
    'far away from',
    'before',
    'after',
    'to the left of',
    'to the right of',
    'beside',
    'over',
    'under',
    'on top of',
    'in between',
    'next to',
    'behind',
    'in front of'
]

articles = [
    'a',
    'an',
    'the'
]