verbs = [
    'being',
    'having',
    'doing',
    'saying',
    'going',
    'getting',
    'making',
    'taking',
    'seeing',
    'using',
    'giving',
    'asking',
    'holding',
    'putting',
    'pushing',
    'running',
    'dancing',
    'singing',
    'eating',
    'finding',
    'writing',
    'sitting',
    'wearing',
]

prepositions = [
    'with',
    'on',
    'above',
    'below',
    'inside', # not 'in' since it is a keyword
    'outside',
    'near',
    'far away from',
    'before',
    'after',
    'to the left of',
    'to the right of',
    'beside',
    'over',
    'under',
    'on top of',
    'in between',
    'next to',
    'behind',
    'in front of'
]